### ISSUE TITLE
Describe collaborations

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/neuroinformatics-unit.github.io#76]
We should only include public projects that we can link to. This may be a good place to also outline #58

**Comment by adamltyson** [comment]
Also:
* Keshavarzi lab (movement & datashuttle)
* AMF (brainglobe-stitch etc. )

**Comment by alessandrofelder** [comment]
Do
* Advanced Research Computing: general BrainGlobe (packaging, benchmarks, ...)
* Akrami Lab: BrainGlobe atlas validation and generation
count?

**Comment by adamltyson** [comment]
Probs yes to everything

**Comment by adamltyson** [comment]
Just the level of detail may vary (e.g. with ARC we have a longstanding collab with multiple people, leading to specific outcomes).

**Comment by JoeZiminski** [comment]
Yes I agree we can count spikeinterface as collaboration, also UNLE when released. None others come to mind at the moment but will keep thinking.
