### ISSUE TITLE
Add team members to `People` section of the website

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/neuroinformatics-unit.github.io#87]
New [entries](https://neuroinformatics.dev/people.html) can be copied and pasted from [existing ones](https://github.com/neuroinformatics-unit/neuroinformatics-unit.github.io/blob/main/docs/source/people.md).

**Comment by sfmig** [comment]
just FYI it took me a while to notice in the pics grid there were two nested levels 😅.
The whole grid is wrapped around :::: but each card is wrapped around ::: (4 vs 3 colons). 

More details in [the docs](https://sphinx-design.readthedocs.io/en/latest/grids.html#placing-a-card-in-a-grid)
